# Generated by Django 5.2.3 on 2025-07-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_number_user_phone_alter_user_auth_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('email', 'email'), ('phone_number', 'phone_number')], max_length=31),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='verify_type',
            field=models.CharField(choices=[('email', 'email'), ('phone_number', 'phone_number')], max_length=31),
        ),
    ]
