# Generated by Django 5.2.3 on 2025-07-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_user_phone_number_alter_user_auth_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='expiretion_time',
            new_name='expiration_time',
        ),
    ]
